/*
samplecrd by justxuewei
inspired by https://time.geekbang.org/column/article/41876
*/
// Code generated by client-gen. DO NOT EDIT.

// This package contains the scheme of the automatically generated clientset.
package scheme
