/*
samplecrd by justxuewei
inspired by https://time.geekbang.org/column/article/41876
*/
// Code generated by client-gen. DO NOT EDIT.

// Package fake has the automatically generated clients.
package fake
