/*
samplecrd by justxuewei
inspired by https://time.geekbang.org/column/article/41876
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkNamespaceListerExpansion allows custom methods to be added to
// NetworkNamespaceLister.
type NetworkNamespaceListerExpansion interface{}
