/*
samplecrd by justxuewei
inspired by https://time.geekbang.org/column/article/41876
*/
// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated clientset.
package versioned
