apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
  labels:
    type: rook-ceph-block-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: rook-ceph-block
